### ISSUE TITLE
Can't find jar files

### ISSUE THREAD

**Issue by johnwuelk** [briacp/SDLPPXPackager#1]
I can't find the jar files in the package after git clone [path]. How can I compile the whole thing? Or could you provide the jar files? There is no such description in the readme file. Thank you.

**Comment by briacp** [comment]
The latest jar can be found in the release page: https://github.com/briacp/SDLPPXPackager/releases/tag/v1.2.1 

You can also compile the project with the following command: `gradlew jar`

**Comment by johnwuelk** [comment]
Thank you so much!
I overlooked the link to releases...
